version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  promotrackerbot:
    build: .
    ports:
      - 8000:8000
    environment:
      TELEGRAM_TOKEN: "$TELEGRAM_TOKEN"
      REDIS_HOST: redis
    depends_on:
      - redis
  # tests:
  #   image: "local/signals-api"
  #   command: pytest -x --no-cov
  #   environment:
  #     REDIS_HOST: redis
  #   depends_on:
  #     - redis
