version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  promotrackerbot:
    build:
      context: .
      args:
        TELEGRAM_BOT_TOKEN: "$TELEGRAM_TOKEN"
        REDIS_HOST: "$REDIS_HOST"
        REDIS_PORT: "$REDIS_PORT"
    ports:
      - 8000:8000
    depends_on:
      - redis
